version: 2.1
executors:
    docker-image:
      docker:
        - image: 'cimg/base:stable'
jobs:
    build:
        executor: my-executor
        steps:
            - checkout
            - run:
                command: "sudo npm install -g npm@latest"  
                - restore_cache:
                    key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules      
    checklint:
        executor: my-executor
        steps:
            - checkout
            - run:
                command: npm run lint    
orbs:
    node: circleci/node@3.0.0
workflows:
    test_my_app:
      jobs:
        - build:
            filters:
                branches:
                    only: master  
        - checkout:
            requires:
                - build
            filters:
                branches:
                    only: master    