version: 2.1
executors:
    docker-image:
      docker:
        - image: circleci/node:dubnium-buster-browsers-legacy
jobs:
    build:
        executor: docker-image
        steps:
            - checkout
            - run:
                command: "sudo npm install -g npm@latest"  
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - node/install:
                install-yarn: true
                node-version: latest
            - run: node --version        
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ../node_modules           
    checklint:
        executor: docker-image
        steps:
            - checkout 
            - run:
                command: npm run lint --path ../node_modules    
orbs: 
    node: circleci/node@3.0.0
workflows:
    test_my_app:
      jobs:
        - build:
            filters:
                branches:
                    only: master  
        - checklint:
            requires:
                - build
            filters:
                branches:
                    only: master    
