version: 2.1
executors:
    docker-image:
      docker:
        - image: circleci/node:dubnium-buster-browsers-legacy
jobs:
    build:
        executor: docker-image
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: Install dependencies with NPM
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules              
    checklint:
        executor: docker-image
        steps:
            - checkout 
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules   
            - run:
                command: npm run lint    
workflows:
    test_my_app:
      jobs:
        - build:
            filters:
                branches:
                    only: master  
        - checklint:
            requires:
                - build
            filters:
                branches:
                    only: master    
