const router=require('koa-router')()
const article=require('../../controller/admin/article')
const auth=require('../../utils/auth')
router.post('/insertArticleData',auth(),article.insertData)
      .post('/queryArticle',auth(),article.queryArticle)
      .post('/deleteArticleById',auth(),article.deleteArticleById)
      .post('/findArticleById',auth(),article.findArticleById)
      .post('/updateArticleById',auth(),article.updateArticleById)
      .get('/getArticleList',auth(),article.getArticleList)
module.exports=router.routes()