const router=require('koa-router')()
const article=require('../../controller/admin/article')
const auth=require('../../utils/auth')
router.post('/insertArticleData',auth(),article.insertData)
module.exports=router.routes()