const router=require('koa-router')()
const user=require('./user')
const visitor=require('./visitor')
const tag=require('./tag')
const link=require('./link')
const article=require('./article')
router.use('/user',user)
router.use('/visitor',visitor)
router.use('/tag',tag)
router.use('/link',link)
router.use('/article',article)
module.exports=router.routes()
